baseURL = "https://flizou.github.io/rapportdestage/"
languageCode = "fr-fr"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = false

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "fr"

# Site Params
[params]
logo = "logo.jpg"
# Gestion des langues : FR / EN / NL / DE
[[Params.listeLangues]]
code = "fr"


# meta data
author = "Themefisher"
description = "This is meta description"

# Gestion des langues : FR / EN / NL / DE
[Languages]
############ 1 - Site en FRANCAIS
[Languages.fr]
weight = 1
languageCode = "fr-fr"
title = "Rapport de Stage Florian Muet 2SN"
dateFormat = "2 Janvier 2006"

home = "Accueil"
logo = "images/image4.jpg"
menufixed = true

footerDescription = "FRANCAIS Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Services"
footerQuicklinkTitle = " Liens Rapide"
footerAboutTitle = "Sur nos réseaux sociaux"
footerSubscribeTitle = "Suivez-Nous"

# Hero Area Section
[Languages.fr.params.hero]
enable = true
heading = "Mon Rapport de Stage"
description = "Voici mon rapport de stage."
button = true
btnText = "Pour en savoir +"
btnURL = "http://localhost:1313/blog/"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.fr.params.aboutSm]
enable = true
title = " Nous explorons le paysage numérique avec passion depuis longtemps"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

# Blog Section On Homepage
[Languages.fr.params.blog]
enable = true
topTitle = "OUR UNTOLD STORY"
title = "Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.fr.params.contact]
enable = true
topTitle = "Prends des notes"
title = "Contactez-Nous"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "14/05, Stockhome <br> Victori Palace , United States"
phone = "(03) 9283 2617"
fax = "+61 3827 3590"
facebook = "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin = "https://www.linkedin.com/"
dribbble = "https://youtube.com/"
instagram = "https://www.instagram.com/flizou__ytb/"
mapLatitude = "51.507351"
mapLongitude = "-0.127758"
mapMarker = "images/marker.png"

# Call to Action Section on About Page
[Languages.fr.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "FRANCAIS Créons quelque chose ensemble"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Nous contacter"


# cookies
[params.cookies]
enable = true
expire_days = 2
# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "about"
url = "about/"
weight = 2
[[menu.nav]]
name = "service"
url = "service/"
weight = 3
[[menu.nav]]
name = "portfolio"
url = "portfolio/"
weight = 4
[[menu.nav]]
name = "blog"
url = "blog/"
weight = 5
[[menu.nav]]
name = "contact"
url = "contact/"
weight = 6

# Footer Service Menu
[[menu.service]]
name = "graphicdesign"
url = "service/"
weight = 1
[[menu.service]]
name = "webdesign"
url = "service/"
weight = 2
[[menu.service]]
name = "webdevelopment"
url = "service/"
weight = 3

# Footer Quick links Menu
[[menu.quicklink]]
name = "partners"
url = "about/"
weight = 1
[[menu.quicklink]]
name = "about"
url = "about/"
weight = 2
[[menu.quicklink]]
name = "faqs"
url = "about/"
weight = 3
[[menu.quicklink]]
name = "badges"
url = "about/"
weight = 4
